name: willing_form
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter_glow: ^0.2.0
  google_fonts: ^2.2.0
  flutter_signin_button: ^2.0.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.1
  firebase_database: ^9.0.6
  animated_text_kit: ^4.2.1
  provider: ^5.0.0
  syncfusion_flutter_xlsio:
  flutter_share: ^2.0.0
  contactus: ^1.2.0
  cloud_firestore: ^3.1.8
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.0
  cupertino_stepper: ^0.2.1
  flutter_dropdown: ^1.0.0+hotfix.1
  dropdown_button2: ^1.2.2
  file_picker: ^4.5.1
  excel: ^2.0.0-null-safety-3

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter


flutter: 
  uses-material-design: true
  assets:
    - assets/images/

